### ISSUE TITLE
Generate hook is not working

### ISSUE THREAD

**Issue by Defite** [Gomah/nuxt-ghost#1]
Hey. I'm using your hook from readme to generate blog pages. Copy/pasted it to modules dir and turned on in modules section in nuxt.config.js. When I do `yarn generate`, I get error:

```
 FATAL  Cannot read property 'nuxt' of undefined                                                  23:41:42

  at ModuleContainer._default (modules/ghost.js:8:8)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

Any thoughts on what I did wrong?

**Comment by Gomah** [comment]
Hey @Defite,

Fixed now in the new version, I updated the docs: https://nuxt-ghost.vercel.app/helpers/generate-sitemap

**Comment by Defite** [comment]
Thank you, @Gomah! The only thing - I think it must be:

```
import GhostContentAPI from '@tryghost/content-api';
```

instead of

```
import { GhostContentAPI } from 'nuxt-ghost';
```

Because if I import GhostContentAPI from your package, I got this error:

```
TypeError: _nuxtGhost.GhostContentAPI is not a constructor
```

**Comment by Gomah** [comment]
You can use both since 2.0.8 is exposing `GhostContentAPI`:

https://github.com/Gomah/nuxt-ghost/blob/master/lib/module.js#L27

**Comment by Defite** [comment]
> You can use both since 2.0.8 is exposing `GhostContentAPI`:
> 
> https://github.com/Gomah/nuxt-ghost/blob/master/lib/module.js#L27

My bad - forgot to update module)
